version: "3"
services:

  db:
    image: neo4j:3.3
    volumes:
      - ./data/neo4j/log:/var/lib/neo4j/logs
      - ./data/neo4j/graph.db:/var/lib/neo4j/data/graph.db
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none

  tileserver:
    image: klokantech/tileserver-gl:v2.2.0
    volumes:
      - ./data/maptiles:/data
    ports:
      - 8080:80
